# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

draw_Wt_b_cpp <- function(omegat_inv, Mnt, tau, sigmatb, pt, qt, B) {
    .Call(`_BayesRegDTR_draw_Wt_b_cpp`, omegat_inv, Mnt, tau, sigmatb, pt, qt, B)
}

